workspace 'Lyst.xcworkspace'
platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!

def provider_pods
    pod 'Moya', '~> 8.0'
    pod 'Result', '~> 3.0'
end

target 'Lyst' do
    provider_pods
    pod 'Haneke'
end

target 'LystProvider' do
    project '../LystProvider/LystProvider.xcodeproj'
    provider_pods
end
